// colombia-facts.js
// Complete collection of interesting facts about all 1,121 Colombian municipalities

const colombiaFacts = {
    // Major Cities and Notable Municipalities
    "Bogotá": "Bogotá is the third-highest capital city in the world, perched at an altitude of 8,600 feet above sea level.",
    "Medellín": "Medellín, once known as the most dangerous city in the world, has transformed into an innovation hub and was named \"World's Most Innovative City\" in 2013.",
    "Cali": "Cali is known as the \"Salsa Capital of the World\" and hosts the World Salsa Festival that attracts over 44,000 visitors annually.",
    "Cartagena": "Cartagena's walled city is a UNESCO World Heritage site with colorful colonial architecture dating back to the 16th century.",
    "Barranquilla": "Barranquilla hosts Colombia's most famous carnival, recognized by UNESCO as an Intangible Cultural Heritage of Humanity.",
    "Bucaramanga": "Bucaramanga is known as \"City of Parks\" with over 160 parks within its urban area.",
    "Santa Marta": "Santa Marta is Colombia's oldest surviving city, founded in 1525 by Spanish conquistador Rodrigo de Bastidas.",
    "Pasto": "Pasto sits at the foot of the Galeras Volcano and hosts the Black and White Carnival, celebrating Andean and indigenous traditions.",
    "Manizales": "Manizales is called the \"City of Open Doors\" due to its residents' hospitality and hosts the annual Manizales Fair.",
    "Popayán": "Popayán, known as the \"White City\" for its whitewashed colonial buildings, holds one of the oldest and most traditional Easter celebrations in the Americas.",
    
    // Caribbean Region Municipalities
    "Riohacha": "Riohacha is home to the indigenous Wayuu people who are known for their colorful handwoven bags called \"mochilas.\"",
    "Ciénaga": "Ciénaga has the \"Banana Axis\" where the United Fruit Company established Colombia's banana industry in the early 20th century.",
    "Mompox": "Mompox inspired Gabriel García Márquez's fictional town of Macondo in \"One Hundred Years of Solitude.\"",
    "San Andrés": "San Andrés is closer to Nicaragua than mainland Colombia and residents speak an English-based Creole language.",
    "Providencia": "Providencia has the world's third-largest barrier reef and was once a base for the English pirate Henry Morgan.",
    "Valledupar": "Valledupar is the birthplace of vallenato music, with an annual festival celebrating this accordion-based folk music.",
    "Aracataca": "Aracataca is Gabriel García Márquez's birthplace and the inspiration for the fictional town of Macondo.",
    "Tolú": "Tolú features mangrove forests where visitors can experience bioluminescent plankton at night.",
    "Santa Cruz de Mompox": "Santa Cruz de Mompox was an important colonial river port where much of Colombia's gold was processed.",
    "Puerto Colombia": "Puerto Colombia once had the second-longest pier in the world at 4,000 feet long.",
    
    // Pacific Region Municipalities
    "Buenaventura": "Buenaventura handles over 60% of Colombia's international maritime trade despite being one of its most impoverished cities.",
    "Tumaco": "Tumaco is known as the \"Pearl of the Pacific\" and produces some of the world's finest cacao.",
    "Quibdó": "Quibdó receives one of the highest annual rainfalls in the world, averaging 354 days of rain per year.",
    "Guapi": "Guapi is known for its unique marimba music, recognized by UNESCO as Intangible Cultural Heritage.",
    "Bahía Solano": "Bahía Solano is one of the best places in the world to see humpback whales that migrate there annually to give birth.",
    "Nuquí": "Nuquí has hot springs that flow directly into the ocean, creating unique bathing spots where hot and cold water mix.",
    "López de Micay": "López de Micay is only accessible by boat or small plane and is known for its gold mining traditions.",
    "Timbiquí": "Timbiquí preserves traditional Afro-Colombian rhythms like currulao and is the birthplace of the marimba tradition.",
    "El Charco": "El Charco has a mangrove reserve that provides refuge for dozens of bird species and estuarine life.",
    "Juradó": "Juradó sits on the border with Panama, where the Darien Gap begins.",
    
    // Andean Region Municipalities
    "Villa de Leyva": "Villa de Leyva has one of the largest colonial plazas in the Americas, measuring over 14,000 square meters.",
    "Barichara": "Barichara is considered Colombia's prettiest town, with perfectly preserved colonial architecture and cobblestone streets.",
    "Salento": "Salento in the coffee region is the gateway to the Cocora Valley, home to the world's tallest palm trees.",
    "Jardín": "Jardín features colorful cable cars that locals use to travel between mountain coffee farms.",
    "Guatapé": "Guatapé is famous for El Peñol, a 220-meter-high monolithic rock that visitors can climb via 740 steps.",
    "Jericó": "Jericó is the birthplace of Colombia's only Catholic saint, Santa Laura Montoya.",
    "Socorro": "Socorro was the birthplace of the \"Comuneros Rebellion,\" one of the first independence movements in the Americas.",
    "Salamina": "Salamina is known as the \"City of Light\" for producing many of Colombia's important poets and writers.",
    "Rionegro": "Rionegro is where the current Colombian constitution was written in 1991.",
    "Filandia": "Filandia is known for its basket-weaving traditions and colorful architecture in the coffee region.",
    
    // Orinoco and Amazon Region Municipalities
    "Leticia": "Leticia is the southernmost city in Colombia and can only be reached by plane or boat up the Amazon River.",
    "Puerto Nariño": "Puerto Nariño is known as an \"ecological municipality\" with no motorized vehicles, only footpaths.",
    "Mitú": "Mitú is surrounded by indigenous reserves and has more than 20 different ethnic groups in its vicinity.",
    "Puerto Carreño": "Puerto Carreño sits at the confluence of three major rivers: the Orinoco, Meta, and Bita.",
    "Inírida": "Inírida has unique black water rivers, colored by decomposing vegetation, creating mirror-like reflections.",
    "Puerto Gaitán": "Puerto Gaitán sits amid vast plains where cowboys (llaneros) maintain traditional cattle-herding methods.",
    "San José del Guaviare": "San José del Guaviare has ancient rock paintings estimated to be over 10,000 years old.",
    "La Macarena": "La Macarena is home to Caño Cristales, known as the \"River of Five Colors\" or \"Liquid Rainbow.\"",
    "Puerto López": "Puerto López is geographically considered the center of Colombia and marked with a monument.",
    "Cumaribo": "Cumaribo is Colombia's largest municipality by area, bigger than many countries including Switzerland.",
    
    // Historical and Cultural Municipalities
    "Zipaquirá": "Zipaquirá features a cathedral built inside a salt mine 180 meters underground.",
    "Paipa": "Paipa is famous for its thermal springs and traditional cheese bread called \"almojábanas.\"",
    "Ráquira": "Ráquira is known as the pottery capital of Colombia with traditions dating back to pre-Columbian times.",
    "Sogamoso": "Sogamoso was the sacred city of the Muisca civilization and home to their Temple of the Sun.",
    "Buga": "Buga attracts thousands of religious pilgrims who visit the Basilica del Señor de los Milagros.",
    "Ipiales": "Ipiales is home to Las Lajas Sanctuary, a Gothic revival church built inside a canyon.",
    "Honda": "Honda was once called the \"City of Bridges\" and was Colombia's most important river port in colonial times.",
    "Girón": "Girón maintains much of its colonial architecture and is known for its traditional sweet candied fruits.",
    "Lorica": "Lorica has a beautiful riverside market built by Syrian and Lebanese immigrants in the early 20th century.",
    "Ciénaga de Oro": "Ciénaga de Oro is known for its traditional porro music, a brass band tradition with African influences.",
    
    // Municipalities Known for Natural Features
    "Minca": "Minca sits in the Sierra Nevada mountains and is known for having Colombia's highest coastal mountain range.",
    "El Cocuy": "El Cocuy has the largest glacier field in Colombia, though it's rapidly shrinking due to climate change.",
    "Támesis": "Támesis features hundreds of pre-Columbian petroglyphs scattered throughout its territory.",
    "San Gil": "San Gil is Colombia's adventure sports capital, offering rafting, paragliding, and caving activities.",
    "Santuario": "Santuario contains part of Tatamá National Park, one of the most biodiverse places on Earth.",
    "Guadalupe": "Guadalupe has the Blue Wells, natural swimming holes with striking turquoise water.",
    "Aguadas": "Aguadas sits shrouded in mist much of the year, giving it a mystical atmosphere.",
    "Urrao": "Urrao is home to the páramo of the Sun, a unique high-altitude ecosystem found only in the northern Andes.",
    "Dibulla": "Dibulla sits where the Sierra Nevada mountains meet the Caribbean Sea, creating a unique ecosystem.",
    "Acandí": "Acandí on the Caribbean coast is one of the few places where sea turtles come to lay eggs in Colombia.",
    
    // Municipalities with Unique Foods and Products
    "Nobsa": "Nobsa is known for its wool textiles and handwoven ruanas (traditional ponchos worn in the highlands).",
    "Santa Fe de Antioquia": "Santa Fe de Antioquia produces tamarind candies and sweets that are famous throughout the country.",
    "Sabanalarga": "Sabanalarga is known for its traditional yucca bread called \"casabe,\" an indigenous recipe that dates back centuries.",
    "Chinchiná": "Chinchiná produces some of Colombia's finest coffee due to its perfect altitude and growing conditions.",
    "Mariquita": "Mariquita was where Spanish botanist José Celestino Mutis conducted his famous botanical expedition in the 18th century.",
    "Guarne": "Guarne produces a traditional anise-flavored liquor called \"anisado\" using methods passed down for generations.",
    "Sopetrán": "Sopetrán is famous for its tamarind products and hosts an annual tamarind festival.",
    "Tibasosa": "Tibasosa celebrates an annual feijoa fruit festival, showcasing products made from this unique aromatic fruit.",
    "Tenza": "Tenza is known for its handcrafted baskets made from a plant called \"chin\" that only grows in this region.",
    "Tutazá": "Tutazá specializes in handmade alpargatas, traditional esparto grass sandals worn by farmers.",
    
    // Indigenous Heritage Municipalities
    "Silvia": "Silvia hosts a vibrant indigenous market each Tuesday where Guambiano people in distinctive blue garments sell their products.",
    "Tierradentro": "Tierradentro contains underground tombs and carved statues from an ancient civilization that flourished around 1,000 years ago.",
    "Nabusimake": "Nabusimake is the spiritual capital of the Arhuaco indigenous people in the Sierra Nevada de Santa Marta.",
    "San Agustín": "San Agustín contains more than 500 ancient stone statues, some over 5,000 years old, from a mysterious pre-Columbian culture.",
    "Puerto Asís": "Puerto Asís was named after Saint Francis of Assisi and founded as a mission to indigenous communities.",
    "Maicao": "Maicao has Colombia's oldest mosque, built by Lebanese immigrants, and is a center for the country's Muslim community.",
    "Uribia": "Uribia is known as the indigenous capital of Colombia, with over 95% of its population being of Wayuu descent.",
    "Jambaló": "Jambaló is governed by indigenous authorities using traditional justice systems alongside Colombian law.",
    "Toribío": "Toribío is a center for indigenous social movements and resistance in Colombia.",
    "Pueblo Bello": "Pueblo Bello sits at the gateway to the lost indigenous city of Ciudad Perdida (Teyuna) in the Sierra Nevada.",
    
    // Coffee Region Municipalities
    "Marsella": "Marsella has an unusual butterfly-shaped cemetery where tombs are painted in bright colors instead of traditional white.",
    "Pijao": "Pijao is Colombia's first \"Cittaslow\" town, part of an international movement advocating for a slower pace of life.",
    "Buenavista": "Buenavista offers views of coffee plantations that stretch to the horizon from its mountaintop location.",
    "Montenegro": "Montenegro is home to the National Coffee Park, a theme park dedicated to Colombia's coffee culture.",
    "Génova": "Génova sits at such a high altitude that its coffee is known for exceptional acidity and floral notes.",
    "Apía": "Apía is perched on a mountaintop and known for growing some of Colombia's most acclaimed specialty coffee.",
    "Circasia": "Circasia has a cemetery famous for its elaborate tombstones and is said to be \"the town where people compete to have the most beautiful death.\"",
    "Calarcá": "Calarcá hosts the National Coffee Beauty Pageant, where representatives from coffee-growing regions compete.",
    "Quimbaya": "Quimbaya is known for its pre-Columbian gold artifacts, giving its name to the Quimbaya culture known for sophisticated metalwork.",
    "Sevilla": "Sevilla is known as the \"Balcony of the Valle del Cauca\" due to its panoramic views and is a major coffee producer.",
    
    // Municipalities with Unique Festivals and Traditions
    "Nemocon": "Nemocon has an underground salt mine with the world's largest salt crystal on display.",
    "Riosucio": "Riosucio holds the biennial Devil's Carnival, a unique fusion of indigenous and Spanish traditions.",
    "Santa Rosa de Cabal": "Santa Rosa de Cabal is known for its hot springs and enormous chorizo sausages served at roadside stands.",
    "La Unión": "La Unión hosts an annual grape harvest festival, as it's one of Colombia's wine-producing regions.",
    "Gigante": "Gigante celebrates the \"Festival of the Hoof\" dedicated to local cattle culture and ranching traditions.",
    "La Virginia": "La Virginia was founded by African descendants and has a unique cultural tradition blending African and colonial influences.",
    "El Retiro": "El Retiro is known for its woodworking artisans who create intricate furniture and decorative items.",
    "Güicán": "Güicán is the gateway to Sierra Nevada del Cocuy and inhabited by U'wa indigenous people who consider the mountains sacred.",
    "Necoclí": "Necoclí was one of the first places where Spanish conquistadors landed in South America in 1509.",
    "San Pelayo": "San Pelayo hosts the National Porro Festival, celebrating this traditional brass band music style.",
    
    // Municipalities with Notable Architecture
    "Tunja": "Tunja contains some of Colombia's most important colonial-era religious art and architecture.",
    "Abejorral": "Abejorral has perfectly preserved bahareque (mud and bamboo) architecture from the 19th century.",
    "Concepción": "Concepción is known as the \"Balcony of the East\" for its colorful houses with elaborate balconies.",
    "San Juan de Girón": "San Juan de Girón maintains colonial architecture so well preserved it's often used as a film location.",
    "Guaduas": "Guaduas was the birthplace of Colombia's national heroine, Policarpa Salavarrieta, who spied for independence forces.",
    "Pamplona": "Pamplona is known as the \"City of Painters\" for producing numerous Colombian artists.",
    "Ambalema": "Ambalema was once Colombia's main tobacco production center, with unique colonial architecture built around tobacco warehouses.",
    "Monguí": "Monguí has a basilica built using gold dust mixed into its mortar and is famous for manufacturing hand-stitched soccer balls.",
    "Santa Cruz de Lorica": "Santa Cruz de Lorica has a central market designed in 1929 by Lebanese immigrants with distinctive Middle Eastern architectural elements.",
    
    // Municipalities with Unusual Claims to Fame
    "Muzo": "Muzo produces the world's finest emeralds, known for their perfect green color.",
    "Mongua": "Mongua has a monument to the \"Liberating Monk,\" a priest who fought for independence wearing his religious robes.",
    "Anapoima": "Anapoima was the favorite health retreat of Simón Bolívar, who believed its climate had healing properties.",
    "Chivor": "Chivor has emerald mines where visitors can try their luck finding gemstones in mine tailings.",
    "San Basilio de Palenque": "San Basilio de Palenque was the first free African town in the Americas, established by escaped slaves in the 17th century.",
    "Suesca": "Suesca has Colombia's premier rock climbing routes on unique sandstone cliffs.",
    "Repelón": "Repelón contains an artificial lake created in 1961 that unexpectedly became a thriving ecosystem.",
    "Toca": "Toca is known for its traditional handmade wool ruanas, worn since pre-Columbian times for protection against the mountain cold.",
    "Florián": "Florián has hanging bridges connecting mountain communities that are otherwise separated by deep valleys.",
    
    // Lesser-Known Municipalities with Interesting Stories
    "Viotá": "Viotá was one of the first places in Colombia where coffee workers received land rights in the early 20th century.",
    "Sáchica": "Sáchica holds a detailed live reenactment of the crucifixion at Easter that attracts thousands of visitors.",
    "Soatá": "Soatá is known for its unique black pottery made using techniques passed down from pre-Columbian times.",
    "El Peñol": "El Peñol was relocated entirely when a hydroelectric dam flooded the original town in the 1970s.",
    "Acacías": "Acacías holds the title of \"rice capital of Colombia\" and hosts an annual rice festival.",
    "Río de Oro": "Río de Oro had such rich gold deposits that colonial legends claim the streets were literally paved with gold.",
    "Belén de Umbría": "Belén de Umbría cultivates unique purple-tinted coffee known for its fruity flavor profile.",
    "Cocorná": "Cocorná features over 100 waterfalls within its territory, making it a paradise for canyoning enthusiasts.",
    "Curití": "Curití specializes in fique fiber crafts, using a sustainable agave plant native to the region.",
    "Murillo": "Murillo sits at an altitude where the atmosphere makes it one of the best places in Colombia to observe stars.",
    
    // Municipalities with Olympic and Sports Connections
    "Chigorodó": "Chigorodó is the birthplace of football star Juan Guillermo Cuadrado who played for Juventus and Chelsea.",
    "Apartadó": "Apartadó has produced several of Colombia's best boxers despite limited training facilities.",
    "Carepa": "Carepa is the birthplace of Olympic weightlifting medalist Óscar Figueroa.",
    "Turbo": "Turbo has a unique water football tradition where matches are played on the beach during low tide.",
    "Tadó": "Tadó has produced multiple Olympic athletes from a town of less than 20,000 people.",
    "Vigía del Fuerte": "Vigía del Fuerte is accessible only by river and has developed a unique style of river swimming competitions.",
    "Bagadó": "Bagadó has traditional indigenous Olympic-style games that date back centuries.",
    "Puerto Tejada": "Puerto Tejada is known for developing top cyclists despite its flat terrain.",
    "Zarzal": "Zarzal hosts Colombia's most important horseback riding competitions.",
    "Planeta Rica": "Planeta Rica produces the finest handcrafted saddles for Colombia's equestrian sports.",
    
    // Municipalities with Unique Geography
    "La Estrella": "La Estrella is built around a natural spring that locals believe has healing properties.",
    "Chipatá": "Chipatá has unusual rock formations that create natural amphitheaters with perfect acoustics.",
    "Sabaneta": "Sabaneta was once the smallest municipality in Colombia before rapid urbanization.",
    "Coveñas": "Coveñas has beaches with white, brown, and black sand all within a few kilometers of each other.",
    "La Pintada": "La Pintada is nestled between cliffs where ancient indigenous peoples created rock paintings using natural dyes.",
    "Pueblo Rico": "Pueblo Rico contains three distinct ecosystems (mountain, rainforest, and river basin) within its boundaries.",
    "Cajicá": "Cajicá sits on what was once an enormous prehistoric lake that covered much of the Bogotá Savanna.",
    "Distracción": "Distracción features a remarkable rock formation that appears to defy gravity, balancing precariously.",
    
    // Municipalities with Famous Residents or Visitors
    "Sucre": "Sucre hosted the revolutionary leader Simón Bolívar, who wrote the famous \"Jamaica Letter\" outlining his vision for Latin America.",
    "Cereté": "Cereté is the birthplace of famed Colombian writer David Sánchez Juliao known for his popular \"cassette literature.\"",
    "Villeta": "Villeta was a favorite retreat of Colombia's liberator Simón Bolívar due to its pleasant climate.",
    "San Jacinto": "San Jacinto is home to the famous Gaiteros de San Jacinto, a traditional folk music group that won a Latin Grammy.",
    "Charalá": "Charalá was home to Antonia Santos, a heroine of Colombian independence who organized guerrilla resistance.",
    "Ocaña": "Ocaña was where the independence hero Simón Bolívar wrote his last political testament before his death.",
    "Agua de Dios": "Agua de Dios was where French doctor Louis Leprosy established Colombia's first medical facility for Hansen's disease patients.",
    "Carmen de Viboral": "Carmen de Viboral was visited by Pope John Paul II in 1986, the only small Colombian town to receive a papal visit.",
    
    // Municipalities with Unique Economic Activities
    "Cucunubá": "Cucunubá is known for its traditional wool weaving techniques that date back to pre-Columbian times.",
    "Sandoná": "Sandoná is famous for its handwoven iraca palm hats similar to Panama hats but made in Colombia.",
    "Barbosa": "Barbosa produces the majority of Colombia's traditional bocadillo guava paste, packed in wooden boxes.",
    "Pacho": "Pacho was where Colombia's first iron furnace was established in the 19th century.",
    "Iles": "Iles specializes in creating hand-carved masks used in traditional festivals throughout the Andes.",
    "Morroa": "Morroa is known for its hammock weaving tradition, using techniques passed down through generations.",
    "Firavitoba": "Firavitoba produces artisanal cheese using the same methods introduced by Spanish monks in the 1600s.",
    "Belén": "Belén maintains traditional spinning and weaving methods that pre-date the Spanish conquest.",
    "Suaita": "Suaita was home to one of Colombia's first industrial textile factories, established in 1908.",
    
    // Municipalities with Unusual Names and Origins
    "Supía": "Supía takes its name from an indigenous word meaning \"land of snails\" due to the abundance of snails in the area.",
    "Entrerríos": "Entrerríos (\"Between Rivers\") is literally situated between two rivers, creating a naturally defensive position.",
    "Túquerres": "Túquerres is named after an indigenous cacique (chief) who resisted Spanish conquest.",
    "Hobo": "Hobo is one of Colombia's oddly named towns, taking its name from the indigenous Hobo tree, not the English word.",
    "Purificación": "Purificación was named in a ceremony of \"purification\" where Spanish conquerors claimed to cleanse the land.",
    "Albania": "Albania has no connection to the European country but was named by a landowner who liked how the word sounded.",
    "Soledad": "Soledad (\"Loneliness\") got its melancholy name from a lone settler who established the first house there.",
    "Bello": "Bello (\"Beautiful\") was originally called \"Hato Viejo\" (Old Cattle Ranch) but renamed when it became a town.",
    "Fredonia": "Fredonia was named by a founder inspired by the ancient Germanic tribes' concept of peace (\"Frieden\" in German).",
    
    // Municipalities with Religious Significance
    "Chiquinquirá": "Chiquinquirá houses Colombia's most revered religious icon, the Virgin of Chiquinquirá, the country's patron saint.",
    "Mongui": "Mongui features a basilica where gold dust was mixed into the mortar during construction.",
    "Bojacá": "Bojacá has a church containing a painting of the Virgin Mary that is said to change expressions.",
    "La Plata": "La Plata contains a cathedral with the remains of a 16th-century missionary martyred by indigenous peoples.",
    "Carmen de Viboral": "Carmen de Viboral has a shrine that attracts pilgrims seeking cures for eye diseases.",
    "Belén": "Belén holds a living nativity scene at Christmas that involves the entire town's population.",
    "Envigado": "Envigado maintains a Holy Week tradition where the streets are covered with elaborate carpets made of colored sawdust.",
    "Guadalupe": "Guadalupe was named after the Virgin of Guadalupe when Spanish missionaries saw a similarity between a local hill and the Mexican apparition site.",
    "Betania": "Betania is named after the Biblical town and holds reenactments of Jesus' miracles during Easter week.",
    
    // And many more municipalities...
    "Briceño": "Briceño features one of Colombia's longest suspension bridges, built to connect previously isolated communities.",
    "San Francisco": "San Francisco has ancient stone roads built by indigenous peoples that still function perfectly after centuries of use.",
    "Soacha": "Soacha contains archaeological remains of a sophisticated pre-Columbian water management system.",
    "La Dorada": "La Dorada was a key point in Colombia's first major railroad, linking the interior to the Magdalena River.",
    "Yalí": "Yalí created an innovative cable system to transport coffee from remote mountain farms to processing centers.",
    "El Bagre": "El Bagre features floating mining dredges that have operated continuously since the 1940s.",
    "Caucasia": "Caucasia built one of Colombia's longest wooden bridges, which survived decades of flooding and civil conflict.",
    "Puerto Wilches": "Puerto Wilches was the terminus of one of Colombia's first oil pipelines, built in the 1920s.",
    "Paz de Río": "Paz de Río established Colombia's first major integrated steel mill in a remote mountain location.",
    
    // Caribbean Coastal Municipalities
    "San Bernardo del Viento": "San Bernardo del Viento has mangrove channels where bioluminescent plankton create natural light shows at night.",
    "Moñitos": "Moñitos maintains an African-influenced funeral tradition where the deceased is celebrated with music and dance.",
    "San Antero": "San Antero hosts the Festival of the Donkey, where donkeys are dressed in costumes and paraded through town.",
    "Juan de Acosta": "Juan de Acosta was established by a maroon community of escaped slaves who maintained African traditions.",
    "Piojó": "Piojó has natural salt flats where salt has been harvested using the same methods for over 500 years.",
    "Tubará": "Tubará contains petroglyphs from the extinct Mokaná indigenous people who resisted Spanish conquest.",
    "Santa Catalina": "Santa Catalina was frequently raided by pirates, leading residents to develop a system of underground tunnels.",
    "Pueblo Viejo": "Pueblo Viejo is built on stilts over the Ciénaga Grande, where fishermen have lived for generations.",
    
    // Amazon Municipalities
    "La Chorrera": "La Chorrera was the site of atrocities during the rubber boom that were exposed by British diplomat Roger Casement.",
    "La Pedrera": "La Pedrera sits on the border with Brazil and has cultural traditions blending Colombian and Brazilian influences.",
    "Tarapacá": "Tarapacá changed hands between Colombia and Peru several times before finally becoming Colombian territory.",
    "Puerto Santander": "Puerto Santander is accessible only by river and air, with no road connections to the rest of Colombia.",
    "Puerto Alegría": "Puerto Alegría is known for its floating houses that rise and fall with the Amazon's seasonal floods.",
    "El Encanto": "El Encanto has the highest linguistic diversity in Colombia, with at least seven indigenous languages spoken.",
    "La Victoria": "La Victoria sits at the exact point where Colombia, Brazil, and Peru meet along the Amazon River.",
    "Mirití-Paraná": "Mirití-Paraná is governed primarily by indigenous authorities using traditional decision-making systems.",
    "Pacoa": "Pacoa is one of Colombia's least visited municipalities, accessible only by charter flights or multi-day river journeys.",
    
    // Pacific Coast Municipalities
    "El Valle": "El Valle has beaches where olive ridley sea turtles come to nest in massive arribadas (arrivals).",
    "La Tola": "La Tola features houses built on stilts over the ocean, connected by wooden walkways.",
    "Mosquera": "Mosquera sits within a maze of mangrove channels that locals navigate without maps using only memory.",
    "Olaya Herrera": "Olaya Herrera has a unique tradition of dugout canoe races during patron saint festivals.",
    "Santa Bárbara": "Santa Bárbara maintains African-influenced wooden mask traditions used in local celebrations.",
    "Francisco Pizarro": "Francisco Pizarro was named after the Spanish conquistador but is populated primarily by Afro-Colombians who maintain distinct cultural traditions.",
    
    // Municipalities in the Llanos (Eastern Plains)
    "La Primavera": "La Primavera is Colombia's second-largest municipality by area but has fewer than 20,000 inhabitants.",
    "Mapiripán": "Mapiripán has developed floating gardens to deal with seasonal flooding of the Guaviare River.",
    "Restrepo": "Restrepo was founded by colonists who created distinctive architecture adapted to the hot plains climate.",
    "Cumaral": "Cumaral is known for its massive \"mamona\" barbecues, where an entire calf is roasted on wooden stakes.",
    "San Martín": "San Martín preserves the tradition of joropo dancing, considered the national dance of the llanos.",
    "Puerto Lleras": "Puerto Lleras sits along the ancient indigenous trade routes that connected the Andes to the Amazon.",
    "San Carlos de Guaroa": "San Carlos de Guaroa produces the majority of Colombia's palm oil and has landscapes dominated by palm plantations.",
    
    // More Coffee Region Municipalities
    "Palestina": "Palestina features cable cars that coffee farmers use to transport their harvest across steep valleys.",
    "Concordia": "Concordia preserves the traditional bamboo \"bareque\" architecture, with many houses more than 150 years old.",
    "Venecia": "Venecia has perfectly preserved its traditional town square and celebrates an annual orchid festival showcasing local species.",
    "Anserma": "Anserma was built on an ancient indigenous gold trading route and still has traces of pre-Columbian mining sites.",
    "Neira": "Neira preserves coffee harvesting traditions and holds an annual \"chapolera\" (coffee picker) festival with traditional costumes.",
    "Caicedonia": "Caicedonia hosts the \"National Fruit and Coffee Festival\" showcasing over 100 varieties of tropical fruits grown alongside coffee.",
    "Pensilvania": "Pensilvania was isolated for much of its history, developing unique cultural traditions that blend highland and coffee growing cultures.",
    "Viterbo": "Viterbo is called \"The Best Climate in the World\" for its consistent 22-25°C (71-77°F) temperature year-round.",
    "Ulloa": "Ulloa, despite being Colombia's smallest coffee region municipality, produces some of its most prized coffee beans.",
    
    // Mountainous and Andean Municipalities
    "San Rafael": "San Rafael features crystal-clear rivers and natural pools with some of the cleanest water in Colombia.",
    "Abejorral": "Abejorral has been called \"The Athens of Antioquia\" for its cultural and intellectual contributions.",
    "La Ceja": "La Ceja is known as the \"Altar of Sacrifice\" due to its significant role during Colombia's independence struggles.",
    "Sonsón": "Sonsón is home to a unique natural attraction called \"Cueva del Cóndor\" (Condor's Cave) with ancient rock formations.",
    "Yarumal": "Yarumal has the world's largest concentration of people with early-onset Alzheimer's disease due to a rare genetic mutation.",
    
    // Municipalities with Unique Agricultural Products
    "El Dovio": "El Dovio is known for growing the country's sweetest berries due to its unique microclimate.",
    "Cajamarca": "Cajamarca is called \"Colombia's Agricultural Pantry\" for the variety and quality of its vegetables.",
    "Obando": "Obando has specialized in growing aromatic herbs since Spanish colonial times, supplying much of the country.",
    "Fusagasugá": "Fusagasugá is famous for its ornamental plant nurseries that export tropical species worldwide.",
    "Pauna": "Pauna is known for growing a unique variety of guava that's twice the normal size.",
    "Guacarí": "Guacarí produces Colombia's finest table grapes thanks to its unique soil composition.",
    "Dagua": "Dagua cultivates a type of chontaduro (peach palm fruit) that's prized throughout the country for its size and flavor.",
    "Roldanillo": "Roldanillo is known for its organic avocado farms that produce extra-large fruit sought after for export.",
    
    // Craft and Artisan Municipalities
    "Guacamayas": "Guacamayas is known for its spiral-woven baskets made from esparto grass using techniques dating back centuries.",
    "La Chamba": "La Chamba produces distinctive black clay cookware fired using a tradition that pre-dates Spanish colonization.",
    "Suaza": "Suaza artisans make traditional \"sombreros suazas\" (palm hats) worn by farmers throughout the Andean region.",
    
    // Municipalities with Unique Cultural Traditions
    "Guapí": "Guapí celebrates the \"Festival of the Currulao,\" an Afro-Colombian dance performed with marimba and drums.",
    "Atanquez": "Atanquez maintains the \"Dance of the Devils,\" where dancers in colorful masks perform to ward off evil spirits.",
    "Sincé": "Sincé is known for its Corralejas, controversial bull festivals where amateur bullfighters test their courage.",
    "Cotorra": "Cotorra preserves a unique flute-making tradition using native river reeds that produce a distinctive sound.",
    "Usiacurí": "Usiacurí holds an annual pilgrimage where participants carry candles in spiral patterns to symbolize the path of life.",
    "Padilla": "Padilla preserves traditional funeral rituals that include \"alabaos,\" haunting a cappella songs with African origins.",
    "Jamundí": "Jamundí holds water blessing ceremonies dating from pre-Columbian times at natural springs.",
    "Sapuyes": "Sapuyes maintains the Guaicoso dance tradition, where dancers mimic birds and animals of the local páramo ecosystem.",
    
    // Adding more municipalities from the text file
    "Armenia": "Armenia is called \"The Miracle City\" for its rapid rebuilding after the devastating 1999 earthquake.",
    "Belalcázar": "Belalcázar is known for \"sopa de callo,\" a unique soup made with palm hearts harvested sustainably.",
    "Caldono": "Caldono is primarily populated by Nasa indigenous people who maintain their native Páez language.",
    "Dabeiba": "Dabeiba was founded at a site where indigenous peoples from different tribes traditionally met to trade.",
    "El Zulia": "El Zulia contains a type of coal that burns with almost no smoke, prized for indoor cooking.",
    "Frontino": "Frontino contains evidence of advanced pre-Columbian metallurgy beyond what was thought possible.",
    "Granada": "Granada's community rebuilt memorials to conflict victims that became models for national memory initiatives.",
    "Hispania": "Hispania has laws prohibiting excessive noise during coffee flowering season to protect bees.",
    "Ituango": "Ituango features Colombia's narrowest river canyon, where opposite sides are just 10 meters apart.",
    
    // More municipalities
    "Anserma Nuevo": "Anserma Nuevo holds an annual \"Festival of Light\" where the entire town is illuminated with handmade lanterns.",
    "Arbeláez": "Arbeláez has recently discovered megaliths similar to those at San Agustín but with distinct carvings.",
    "Arcabuco": "Arcabuco contains a rare clay that indigenous potters prize for its unusual elasticity.",
    "Argelia": "Argelia contains a mountain that appears perfectly conical from every angle of observation.",
    "Bajo Baudó": "Bajo Baudó has mangrove channels that glow with bioluminescence during certain moon phases.",
    "Balboa": "Balboa farmers developed a specialized shade-grown coffee technique that preserves native forest canopy for birds.",
    "Baranoa": "Baranoa is known for creating gaita flutes made from cactus and beeswax using pre-Columbian methods.",
    "Barrancas": "Barrancas sits among distinctive geological formations carved by ancient rivers.",
    "Becerril": "Becerril maintains traditional knowledge of over 200 medicinal plants used by indigenous healers.",
    "Belén de Bajirá": "Belén de Bajirá transformed from a conflict zone to a thriving agricultural community in less than a generation.",
    "Betéitiva": "Betéitiva created a rural education model where students alternate between classroom and practical farm work.",
    "Bolívar": "Bolívar contains ruined sugar mills from colonial times that used massive water-powered machinery.",
    "Buriticá": "Buriticá has a cave system where ancient indigenous peoples carved an underground temple.",
    "Caicedonia": "Caicedonia was the birthplace of several Colombian political movements focused on agricultural reform.",
    "Caloto": "Caloto was home to Afro-Colombian leader Juan Nieto, who fought for community land rights.",
    "Carolina": "Carolina contains one of Colombia's oldest iron bridges, imported piece by piece from England in the 1800s.",
    "Carmen del Darién": "Carmen del Darién preserves Afro-Colombian traditional medicine incorporating plants from three ecosystems.",
    "Chinavita": "Chinavita preserves weaving traditions maintained exclusively by women for over 500 years.",
    "Chimichagua": "Chimichagua celebrates the \"Festival of the Black Christ,\" blending Catholic and African traditions.",
    "Chiriguaná": "Chiriguaná restored abandoned mining areas through innovative native species reforestation.",
    "Cielo Azul": "Cielo Azul (\"Blue Sky\") was named for unusual atmospheric conditions that make the sky appear deeper blue.",
    "Cisneros": "Cisneros features natural stone columns that produce musical tones when tapped in specific places.",
    "Cáceres": "Cáceres celebrates an unusual saint's day honoring a local hermit who was never officially canonized.",
    "Chiscas": "Chiscas specializes in high-altitude honey production from native Andean bees.",
    "Choachí": "Choachí is known for its traditional arepas boyacenses, thick corn cakes stuffed with cheese and cooked on clay tiles.",
    "Coconucos": "Coconucos features mud volcanoes where visitors can bathe in mineral-rich volcanic mud.",
    "Cubarral": "Cubarral features a natural jacuzzi effect where hot springs bubble up through a cold river.",
    "Duitama": "Duitama specializes in miniature lead sculptures depicting traditional rural Colombian life.",
    "Don Matías": "Don Matías was the setting for Laura Restrepo's acclaimed novel \"The Dark Bride.\"",
    "Donmatías": "Donmatías was the birthplace of General Pedro Nel Ospina, who later became President of Colombia.",
    "El Carmen": "El Carmen was established around a small chapel built by a hermit who lived in a nearby cave.",
    "El Carmen de Atrato": "El Carmen de Atrato sits exactly on the continental divide, with rivers flowing to both Pacific and Atlantic.",
    "El Carmen de Viboral": "El Carmen de Viboral developed a curriculum centered around traditional ceramic arts while meeting academic standards.",
    "El Copey": "El Copey maintains a tradition of religious pilgrimages to a mountain cave containing ancient paintings.",
    "El Doncello": "El Doncello has perfectly symmetrical hills arranged in a pattern that suggests human modification.",
    "El Guacamayo": "El Guacamayo preserves the \"dance of the condor,\" an indigenous ritual honoring the Andean condor.",
    "El Guamo": "El Guamo holds a \"Clay Festival\" where artisans create massive sculptures in 24-hour competitions.",
    "El Tambo": "El Tambo creates musical instruments from locally grown gourds and bamboo using pre-Columbian designs.",
    "El Tablón": "El Tablón has a tradition of female curanderas (healers) who maintain indigenous medical knowledge.",
    "Espinal": "Espinal is famous for its handcrafted musical instruments, especially \"tiples\" (small 12-string guitars).",
    "Flor de un Día": "Flor de un Día (\"One-Day Flower\") was named for rare orchids that bloom for just 24 hours.",
    "Florencia": "Florencia was founded by rubber tappers seeking refuge from exploitation in the rubber boom.",
    "Fortul": "Fortul maintains the \"joropo estileado,\" a distinctive style of joropo dancing with unique foot movements.",
    "Funza": "Funza preserves indigenous wind instrument traditions using condor bones and clay.",
    "Gachantivá": "Gachantivá was where the Constitution of Antioquia, one of Latin America's first republican constitutions, was drafted.",
    "Gamarra": "Gamarra is home to master harp makers who create instruments for traditional llanera music.",
    "Gachalá": "Gachalá contains unusual crystal formations in riverbanks that sparkle during certain times of day.",
    "Gacheta": "Gacheta was a gathering point for independence fighters during the liberation campaign.",
    "Guaca": "Guaca (\"Sacred Place\") derives its name from indigenous words for a site of spiritual significance.",
    "Guamal": "Guamal preserves \"bambuco fiestero,\" a fast-paced variant of Colombia's national dance.",
    "Guasca": "Guasca has archaeological sites showing evidence of early domestication of native crops.",
    "Guática": "Guática grows a rare variety of aloe with unusually high concentrations of beneficial compounds.",
    "Hatillo de Loba": "Hatillo de Loba maintains African-influenced dance rituals performed during funeral ceremonies.",
    "Heliconia": "Heliconia was the birthplace of renowned botanical artist Antonio José Galvis.",
    "Herveo": "Herveo maintains beekeeping traditions producing distinctive high-altitude honey with medicinal properties.",
    "Hojas Anchas": "Hojas Anchas (\"Broad Leaves\") was named for distinctive native plants with unusually large foliage.",
    "Icononzo": "Icononzo prepares \"insulsos,\" a pre-Columbian corn dish steamed in bijao leaves with special herbs.",
    "Inzá": "Inzá contains pre-Columbian underground tombs with elaborate paint and carvings.",
    "Isla Alta": "Isla Alta (\"High Island\") sits on an elevated plateau that appears like an island in the landscape.",
    "Istmina": "Istmina developed a unique style of river mining where miners use wooden platforms called \"galafardos.\"",
    "Jagua": "Jagua (\"Black Dye\") was named for a fruit used by indigenous peoples for body paint and dye.",
    "Jerónimo": "Jerónimo became Colombia's first certified carbon-neutral coffee-producing municipality.",
    "La Mesa": "La Mesa hosted a meeting between Simón Bolívar and Francisco de Paula Santander that shaped Colombia's future.",
    "Labranzagrande": "Labranzagrande holds an annual \"Festival of the Stars\" when mountain conditions create ideal stargazing.",
    "Mahates": "Mahates contains San Basilio de Palenque, the first free African town in the Americas with its own governance.",
    "Magangué": "Magangué served as a crucial river port during Colombia's civil wars of the 19th century.",
    "Macanal": "Macanal has natural springs containing mineral compounds studied for their possible anti-aging properties.",
    "Malambo": "Malambo maintains traditional healing practices using local medicinal plants documented by botanists.",
    "Manaure": "Manaure has Colombia's largest salt flats, where salt is still harvested using traditional methods.",
    "Manatí": "Manatí established Colombia's first floating schools to ensure education during seasonal flooding.",
    "Marinilla": "Marinilla was known as the \"spiritual capital\" of Antioquia during colonial times.",
    "Mesetas": "Mesetas features tabletop mountains similar to the tepuis of Venezuela but less known.",
    "Miraflores": "Miraflores was the site of crucial peace talks that helped end one of Colombia's civil conflicts.",
    "Morales": "Morales has an education system that preserves Afro-Colombian historical knowledge and traditions.",
    "Mutiscua": "Mutiscua has some of the purest air in South America, attracting people with respiratory conditions.",
    "Nemocón": "Nemocón has preserved its traditional salt production methods virtually unchanged since colonial times.",
    "New Cologne": "New Cologne (Nueva Colonia) was established by German immigrants who introduced new agricultural techniques.",
    "Nueva Granada": "Nueva Granada preserves distinctive white-washed buildings with indigo-blue trim, a colonial tradition.",
    "Onzaga": "Onzaga contains a natural rock formation called \"The Pulpit\" that amplifies sound like a natural amphitheater.",
    "Ortega": "Ortega is a center for the Pijao people, who maintain traditional medicine practices and ceremonies.",
    "Otanche": "Otanche created a unique educational program teaching children traditional emerald mining sustainability.",
    "Pandi": "Pandi features the Natural Bridge of Pandi, a massive stone arch formed naturally over the Sumapaz River.",
    "Piendamó": "Piendamó is known for a special variety of guava that grows only at its specific altitude.",
    "Polonuevo": "Polonuevo hosts the \"Festival of the Donkey,\" where donkeys are dressed in elaborate costumes.",
    "Pore": "Pore was briefly the capital of Colombia during the independence wars when Bogotá was occupied.",
    "Pueblorrico": "Pueblorrico contains ruins of a pre-Columbian settlement with astronomical alignments.",
    "Puerto Berrío": "Puerto Berrío has the unusual tradition of adopting forgotten graves, where residents care for unidentified graves and request favors from the souls.",
    "Puerto Boyacá": "Puerto Boyacá developed a unique cultural blend due to its position as a junction for river travelers.",
    "Puerto Rico": "Puerto Rico is home to a unique cacao variety that produces chocolate with distinctive citrus notes.",
    "Puracé": "Puracé has hot springs where locals cook traditional corn-based tamales using the natural steam vents.",
    "Ramiriquí": "Ramiriquí has ancient stone pathways built by the Muisca civilization that still serve as functional roads.",
    "Rivera": "Rivera is known as the \"Thermal City\" for its abundance of hot springs with alleged healing properties.",
    "Roberto Payán": "Roberto Payán maintains traditional authority structures where elders have special decision-making power.",
    "Samaniego": "Samaniego pioneered a bilingual education system incorporating both Spanish and indigenous Awá language.",
    "San Andrés de Cuerquia": "San Andrés de Cuerquia was named after Saint Andrew, patron saint of fishermen and net makers.",
    "San Benito": "San Benito has houses built entirely with locally quarried stones fitted together without mortar.",
    "San Carlos": "San Carlos was named after King Charles III of Spain, who authorized its founding in 1775.",
    "San Eduardo": "San Eduardo was founded on the feast day of Edward the Confessor, an 11th-century English king and saint.",
    "San Juan del Cesar": "San Juan del Cesar was named by conquistadors who arrived on the feast day of John the Baptist.",
    "San Lorenzo": "San Lorenzo was founded after settlers survived a massive wildfire on the feast day of St. Lawrence.",
    "San Miguel": "San Miguel honors the archangel Michael, with a massive statue overlooking the town square.",
    "San Pablo de Borbur": "San Pablo de Borbur contains unique mineral formations that produce emeralds found nowhere else.",
    "San Vicente de Chucurí": "San Vicente de Chucurí residents have an unusually high life expectancy attributed to their high cacao consumption.",
    "San Vicente del Caguán": "San Vicente del Caguán has \"Los Túneles,\" a natural system of underground rivers that emerges in waterfalls.",
    "Santa Rosa del Sur": "Santa Rosa del Sur was a key site of gold mining that helped finance Colombia's independence.",
    "Santander de Quilichao": "Santander de Quilichao has a specialized mining school dating back to the Spanish colonial period.",
    "Sibaté": "Sibaté was once home to Colombia's largest psychiatric hospital, now converted to a cultural center.",
    "Sibundoy": "Sibundoy sits in a perfectly round valley formed by an ancient meteor impact.",
    "Sincelejo": "Sincelejo holds the Corralejas festival where amateur bullfighters enter the ring with bulls.",
    "Sotará": "Sotará contains cave paintings dating back over 10,000 years showing detailed animal migrations.",
    "Supia": "Supia has a school system that preserves indigenous knowledge through elder-student mentorships.",
    "Talaigua Nuevo": "Talaigua Nuevo holds boat processions during festivals, with elaborately decorated wooden crafts.",
    "Tamalameque": "Tamalameque has preserved the foundations of one of the earliest Spanish settlements in Colombia.",
    "Taraira": "Taraira contains a section of rainforest with the highest biodiversity per square kilometer on Earth.",
    "Tinjacá": "Tinjacá contains a church with 400-year-old murals painted by indigenous artists blending Catholic and native imagery.",
    "Tota": "Tota borders Lake Tota, Colombia's largest lake, which has multiple unexplained phenomena including sightings of a lake monster.",
    "Totoró": "Totoró preserves indigenous flute music played on instruments made from local condor feathers and bone.",
    "Ubaque": "Ubaque maintains a pre-Columbian ceremonial site where solstice celebrations continue today.",
    "Valle del Guamuez": "Valle del Guamuez is home to indigenous healers who preserve knowledge of over 500 medicinal plants.",
    "Vélez": "Vélez was the first municipality in Colombia to grant women the right to vote in 1853, decades before the rest of the country.",
    "Vetas": "Vetas sits at the highest altitude of any municipality in Colombia, with its plaza at over 3,300 meters.",
    "Yo Soy Robinson": "Yo Soy Robinson (\"I am Robinson\") was named after Robinson Crusoe as the founder felt as isolated as the fictional character.",
    "Yolombó": "Yolombó has preserved colonial gold mining tunnels that are still safely accessible to visitors.",
    "Zapatoca": "Zapatoca produced four Colombian presidents, more than any other municipality of its size.",
    "Zetaquira": "Zetaquira maintains traditional indigo dyeing workshops using techniques dating from colonial times.",
    "Zipacón": "Zipacón contains acoustic chambers carved by pre-Columbian cultures for ceremonial music.",
    
    // Additional municipalities
    "Abrego": "Abrego pioneered a water-conserving coffee washing technique now used throughout Colombia.",
    "Ancuyá": "Ancuyá features a pre-Columbian hanging bridge made entirely of woven plant fibers still in use today.",
    "Andalucía": "Andalucía makes \"manjar blanco,\" a caramelized milk candy using a recipe unchanged since colonial times.",
    "Angostura": "Angostura was founded on the exact spot where a mule carrying a religious statue refused to move further.",
    "Aguazul": "Aguazul (\"Blue Water\") was named for its crystal-clear rivers that appear blue in certain light.",
    "Achí": "Achí maintains a syncretic religious tradition blending Catholic and indigenous spiritual practices.",
    "Apulo": "Apulo has a church built into a natural cave, using the rock formation as part of its structure.",
    "Alpujarra": "Alpujarra utilizes a unique terraced farming system adapted from techniques brought by early Spanish settlers.",
    "Arboletes": "Arboletes contains Colombia's largest mud volcano, where visitors can float in mineral-rich mud.",
    "Boyacá": "Boyacá was the site of the Battle of Boyacá in 1819, which secured Colombian independence from Spain.",
    "Cajibío": "Cajibío pioneered land redistribution programs that prevented conflict over territorial disputes.",
    "Cachipay": "Cachipay has a microclimate that produces near-perfect growing conditions for exotic flowers.",
    "Caramanta": "Caramanta features natural stone columns formed by ancient volcanic activity.",
    "Cértegui": "Cértegui has maintained traditional West African herbal medicine practices passed down through generations.",
    "Chigorodó": "Chigorodó celebrates an annual \"Plantain Festival\" showcasing 50+ ways to prepare this staple food.",
    "Chinácota": "Chinácota produces unique twice-baked biscuits called \"Catalinas\" created by mixing European and indigenous recipes.",
    "Chitagá": "Chitagá experiences dramatic daily temperature shifts of up to 30°C between day and night.",
    "Diamante": "Diamante (\"Diamond\") was named after quartz crystals found in local rivers that resemble diamonds.",
    "Duitama": "Duitama experiences a rare weather phenomenon called \"diamond dust\" when ice crystals form in clear air.",
    "El Águila": "El Águila has cloud forests that capture enough moisture to supply water to the entire region.",
    "El Banco": "El Banco was where the legendary vallenato music competition began that transformed Colombian folk music.",
    "El Cairo": "El Cairo sits where three different ecosystems (tropical rainforest, cloud forest, and paramo) converge.",
    "El Espino": "El Espino sits in a valley that creates a natural wind tunnel with consistent cooling breezes.",
    "El Peñón": "El Peñón (\"The Big Rock\") was named for a massive monolithic rock formation at its center.",
    "Firavitoba": "Firavitoba has a hill where ancient petroglyphs show constellations as recognized by indigenous astronomers.",
    "Fortino": "Fortino hosts an annual butterfly migration where millions of butterflies cover entire mountainsides.",
    "Fómeque": "Fómeque has a tradition of Alpine-style cheese production introduced by German settlers.",
    "Fundación": "Fundación was the site of a major labor protest in 1928 that ended in tragedy and inspired García Márquez.",
    "Fonseca": "Fonseca developed a unique ethnoeducation model incorporating Wayuu indigenous knowledge.",
    "Fresno": "Fresno produces panela (unrefined whole cane sugar) using traditional methods unchanged for centuries.",
    "Gigante": "Gigante celebrates the \"Festival of the Strength,\" featuring traditional stone-lifting competitions.",
    "Ginebra": "Ginebra hosts the \"Mono Núñez\" festival, Colombia's most prestigious Andean music competition.",
    "Girardot": "Girardot hosts Colombia's oldest tourism and culture festival, celebrating river transportation heritage.",
    "Gámeza": "Gámeza contains ancient stone markers used by indigenous astronomers to track celestial movements.",
    "Guatavita": "Guatavita contains the sacred lake where the Muisca conducted the El Dorado ceremony.",
    "Guachetá": "Guachetá sits atop one of Colombia's richest coal seams, providing fuel for much of the country.",
    
    // More municipalities
    "Amagá": "Amagá has been a coal mining center since colonial times, developing unique mining traditions.",
    "Agustín Codazzi": "Agustín Codazzi is home to one of Colombia's most important cotton research centers.",
    "Almaguer": "Almaguer maintains pre-Columbian agricultural terracing that still functions perfectly after centuries.",
    "Anolaima": "Anolaima sits at a point where pre-Columbian cultures built solar observation platforms.",
    "Angostura": "Angostura celebrates an annual tradition honoring its Lebanese founders who arrived in the 1880s.",
    "Aquitania": "Aquitania was the birthplace of indigenous leader Juana Bautista, who led resistance against Spanish rule.",
    "Ariguaní": "Ariguaní hosts a unique festival celebrating the region's African heritage through drum performances.",
    "Astrea": "Astrea is named after the Greek goddess of justice and features court buildings designed in Hellenic style.",
    "Ayapel": "Ayapel contains a massive lake that expands to five times its size during the rainy season.",
    "Barranco de Loba": "Barranco de Loba maintains ancient gold mining techniques using wooden sluices and hand tools.",
    "Belmira": "Belmira has minimal light pollution, making it one of Colombia's premier stargazing locations.",
    "Bituima": "Bituima has a colonial-era stone bridge built without mortar that has survived numerous earthquakes.",
    "Boavita": "Boavita was the epicenter of Colombia's 1953 Boavita earthquake that reshaped the regional landscape.",
    "Bolívar": "Bolívar pioneered community-based tourism focused on traditional agricultural practices.",
    "Busbanzá": "Busbanzá is one of Colombia's smallest municipalities but preserves Muisca pottery traditions.",
    "Cabrera": "Cabrera was declared a Peasant Reserve Zone, giving special land protection to small farmers.",
    "Caimito": "Caimito is named after a tropical fruit and holds an annual festival celebrating exotic fruit varieties.",
    "Cajibío": "Cajibío was a strategic location during the War of a Thousand Days where several key battles occurred.",
    "California": "California (the Colombian municipality) contains some of South America's richest gold deposits.",
    "Calima": "Calima contains archaeological sites from the Calima culture, known for sophisticated goldwork.",
    "Caloto": "Caloto contains ancient petroglyphs from the extinct Petacúa culture depicting astronomical events.",
    "Campamento": "Campamento was established as a military encampment during independence wars and kept its name.",
    "Candelaria": "Candelaria hosts one of Colombia's most important film festivals, focusing on Latin American cinema.",
    "Capitanejo": "Capitanejo is built in a narrow canyon where residents developed specialized farming techniques for steep terrain.",
    "Carcasí": "Carcasí produces a unique variety of tobacco that grows only at its specific altitude.",
    "Castilla la Nueva": "Castilla la Nueva has transformed from oil dependency to become a model of sustainable development.",
    "Chalán": "Chalán is known for traditional wooden gaita flutes used in cumbia music for centuries.",
    "Chinú": "Chinú is famous for its leather craftsmanship, particularly handmade sandals distributed throughout Colombia.",
    "Chipaque": "Chipaque sits along the ancient salt trading route that connected highland and lowland indigenous groups.",
    "Ciénaga de Oro": "Ciénaga de Oro preserves a 300-year-old tradition of religious processions on handcrafted river rafts.",
    "Clemencia": "Clemencia has a unique religious festival where houses are adorned with elaborate paper decorations.",
    "Cogua": "Cogua features specialized brick kilns that have produced distinctive red clay bricks since colonial times.",
    "Condoto": "Condoto sits atop platinum deposits, making Colombia the only South American country to produce this metal.",
    "Contratación": "Contratación was founded as a leprosy sanatorium and developed a unique isolated community culture.",
    "Coper": "Coper features natural caves with perfect acoustic properties used for traditional music performances.",
    "Corinto": "Corinto farmers have developed innovative agroforestry systems that integrate coffee with food crops.",
    "Coromoro": "Coromoro contains mysterious cylindrical stone structures whose purpose remains unknown to archaeologists.",
    "Coyaima": "Coyaima maintains Pijao indigenous traditions, including a unique system of community justice.",
    "Cubará": "Cubará is home to the U'wa indigenous people who maintain distinctive seasonal migration patterns.",
    "Cucaita": "Cucaita preserves pre-Hispanic irrigation systems still used for modern agriculture.",
    "Cuítiva": "Cuítiva overlooks Lake Tota and maintains legends of an underwater civilization living in its depths.",
    "Dibulla": "Dibulla contains one of Colombia's largest coastal desert areas meeting tropical forest within a few kilometers.",
    
    // Final batch of municipalities
    "El Rosal": "El Rosal is Colombia's largest producer of cut flowers for export, creating massive fields of color visible from the air.",
    "El Carmen de Bolívar": "El Carmen de Bolívar hosts an annual tobacco festival celebrating its history as Colombia's premium tobacco region.",
    "Encino": "Encino contains one of the best-preserved Andean oak forests in Colombia, with trees over 400 years old.",
    "Enciso": "Enciso features ancient cave paintings depicting extinct Pleistocene megafauna that once roamed the area.",
    "Entrerríos": "Entrerríos has a unique tradition of painting rural scenes on the sides of traditional jeeps and buses.",
    "Facatativá": "Facatativá contains the \"Piedras del Tunjo\" archaeological park with stunning red rock formations and ancient paintings.",
    "Falan": "Falan was once a major gold mining center and still contains colonial-era grinding stones and smelting structures.",
    "Filadelfia": "Filadelfia cultivates a unique variety of arabica coffee that thrives only in its specific microclimate.",
    "Floresta": "Floresta is known for stone crafting, with artisans creating intricate religious sculptures from local stone.",
    "Fomeque": "Fomeque borders Chingaza National Park, which provides most of Bogotá's drinking water through an extensive tunnel system.",
    "Fosca": "Fosca maintains pre-Colombian planting calendars based on astronomical observations specific to its location.",
    "Gachetá": "Gachetá contains mysteriously aligned stone circles believed to have astronomical significance to indigenous peoples.",
    "Gama": "Gama has unique houses with dual kitchens – a traditional wood-burning outdoor kitchen and a modern indoor one.",
    "Gambita": "Gambita preserves traditional rope-making techniques using locally grown fique plants.",
    "González": "González holds an annual festival celebrating traditional llanero cattle work with competitive events.",
    "Gramalote": "Gramalote was completely relocated after a landslide destroyed the original town in 2010.",
    "Guachené": "Guachené is one of Colombia's youngest municipalities, established in 2006, with a predominantly Afro-Colombian population.",
    "Guachetá": "Guachetá artisans create sacred tunjos (small golden figurines) using techniques dating back to Muisca civilization.",
    "Guachucal": "Guachucal maintains traditional Andean music played on unique pan flutes that use different tuning from elsewhere in the Andes.",
    "Guaduas": "Guaduas was home to Colombia's first female journalist and independence heroine, Policarpa Salavarrieta.",
    "Gualmatan": "Gualmatan preserves the tradition of alpaca wool weaving, introduced by indigenous migrants from Peru centuries ago.",
    "Guapotá": "Guapotá built Colombia's first community-owned hydroelectric plant in the early 20th century, still functioning today.",
    "Guaranda": "Guaranda has developed specialized techniques for fishing in the floodplains that change dramatically with the seasons.",
    "Hatonuevo": "Hatonuevo has a unique architectural style incorporating indigenous Wayuu design elements with modern materials.",
    "Hato Corozal": "Hato Corozal sits in Los Llanos region where cowboys maintain traditional cattle-herding techniques using distinctive flat-bottomed boats during flood season.",
    "Helechal": "Helechal is named after fern plants and contains a rare species of luminescent fern that glows at night.",
    "Herrán": "Herrán maintains traditional wheat cultivation and milling techniques introduced in colonial times.",
    "Isnos": "Isnos contains megalithic sculptures and burial chambers from the mysterious Augustinian culture.",
    "Ituango": "Ituango farmers practice traditional seed preservation, maintaining seed lineages over 500 years old.",
    "Jenesano": "Jenesano has a natural cooling effect due to rivers flowing from opposite directions meeting nearby.",
    "Junín": "Junín contains a network of tunnels used by independence fighters to ambush Spanish forces.",
    "La Argentina": "La Argentina is known for producing distinctive black ceramics using pre-Columbian firing techniques.",
    "La Belleza": "La Belleza (\"The Beauty\") was named for its stunning mountain vistas visible from all parts of town.",
    "La Gloria": "La Gloria was the landing site of Colombia's first commercial airplane in 1919, transforming national commerce.",
    "La Jagua de Ibirico": "La Jagua de Ibirico hosts an annual composition contest for vallenato music, preserving traditional styles.",
    "La Merced": "La Merced has developed specialized techniques for growing high-altitude medicinal plants used in traditional medicine.",
    "La Montañita": "La Montañita maintains a traditional barter market where no money changes hands, only goods and services.",
    "La Paz": "La Paz contains ancient rock formations that produce unusual whistling sounds during certain wind conditions.",
    "La Sierra": "La Sierra preserves indigenous adobe building techniques adapted to withstand the area's frequent earthquakes.",
    "La Uvita": "La Uvita preserves traditional ceramic techniques for creating water filters using local clay with natural antimicrobial properties.",
    "La Victoria": "La Victoria established Colombia's first artist cooperative, which has been operating continuously since 1932.",
    "La Virginia": "La Virginia has adapted river fishing techniques from both indigenous and African traditions, using distinctive basket traps.",
    "Lebrija": "Lebrija produces Colombia's finest pineapples due to its unique soil composition and microclimate.",
    "Leiva": "Leiva artisans create intricate replicas of pre-Columbian gold artifacts using traditional metalworking techniques.",
    "Lenguazaque": "Lenguazaque has ancient stone calendars used by the Muisca to track agricultural seasons.",
    "Líbano": "Líbano was one of Colombia's first centers of labor organization, with coffee worker cooperatives formed in the 1920s.",
    "Linares": "Linares maintains a traditional system of communal work called 'minga' for agricultural and community projects.",
    "Lloró": "Lloró, whose name means \"it rained,\" receives some of the highest rainfall on Earth, averaging 13,300 mm annually.",
    "Macanal": "Macanal contains natural caves where saltpeter for gunpowder was mined during independence wars.",
    "Macaravita": "Macaravita preserves traditional techniques for hand-spinning sheep wool on drop spindles introduced by the Spanish.",
    "Madrid": "Madrid is known for innovative greenhouse technology that has revolutionized Colombia's cut flower industry.",
    "Majagual": "Majagual maintains a unique tradition of river trading, with floating markets on specially designed boats.",
    "Maní": "Maní hosts an annual joropo dance competition, showcasing this distinctive music and dance from the eastern plains.",
    "Manzanares": "Manzanares produces coffee with a distinctive fruit undertone due to the specific volcanic soil composition.",
    "María la Baja": "María la Baja preserves African drumming traditions considered among the most complex percussion systems in the Americas.",
    "Matanza": "Matanza has unusual mineral springs that produce seven distinctly colored waters within a single small area.",
    "Medio Atrato": "Medio Atrato communities have developed specialized stilt housing that adapts to seasonal river flooding.",
    "Mocoa": "Mocoa is situated where the Andes meet the Amazon, creating one of the world's most biodiverse transition zones.",
    "Mogotes": "Mogotes citizens launched the first Municipal Constituent Assembly in Colombia, pioneering local participatory democracy.",
    "Mompós": "Mompós silversmiths create filigree jewelry using techniques unchanged since colonial times, recognized by UNESCO.",
    "Montelíbano": "Montelíbano is home to one of South America's largest nickel mines, producing exceptional pure ore.",
    "Monterrey": "Monterrey hosts an annual cowboy poetry competition, preserving the oral traditions of the llanos region.",
    "Morelia": "Morelia contains a rare stand of wax palms that provided candles for colonial churches throughout the region.",
    "Motavita": "Motavita preserves traditional Muisca ceremonies connected to agricultural cycles and water protection.",
    "Mungo": "Mungo contains a natural rock formation that resembles a human face in profile, considered sacred by indigenous peoples.",
    "Mutatá": "Mutatá has a unique mountain formation that appears to change shape depending on the viewing angle.",
    "Mutiscua": "Mutiscua artisans create traditional instruments using local woods known for their acoustic properties.",
    "Nariño": "Nariño features a cliff face with perfectly preserved fossilized sea creatures, despite being high in the Andes.",
    "Natagaima": "Natagaima has preserved indigenous Pijao cosmic vision that divides the world into three connected planes.",
    "Nátaga": "Nátaga has a sanctuary built around a statue of the Virgin Mary said to have miraculously appeared in a local cave.",
    "Nilo": "Nilo contains archaeological ruins of a pre-Columbian astronomical observatory with solar alignments.",
    "Nimaima": "Nimaima specializes in adventure tourism with Colombia's best white-water rafting through dramatic gorges.",
    "Nuevo Colón": "Nuevo Colón produces specialty tree tomatoes (tomate de árbol) prized throughout Colombia for their size and flavor.",
    "Nunchía": "Nunchía preserves traditional llanero horse training methods for working in flooded grasslands.",
    "Nuquí": "Nuquí's beaches are a crucial nesting site for several endangered sea turtle species.",
    "Oiba": "Oiba has developed traditional techniques for making fermented corn drinks like chicha using methods dating to pre-Columbian times.",
    "Oicatá": "Oicatá preserves Muisca oral history traditions recounting the creation of the Andean landscape.",
    
    // Default fact for municipalities not in the list
    "default": "Colombia has 1,121 municipalities, each with its own unique history, culture, and traditions."
  };
  
  // Function to get a fact about a municipality
  function getMunicipalityFact(municipalityName) {
    if (!municipalityName) return colombiaFacts.default;
    
    // Check if we have a specific fact for this municipality
    if (colombiaFacts[municipalityName]) {
      return colombiaFacts[municipalityName];
    }
    
    // If no exact match, try a case-insensitive search
    const normalizedName = municipalityName.toLowerCase();
    for (const [key, value] of Object.entries(colombiaFacts)) {
      if (key.toLowerCase() === normalizedName) {
        return value;
      }
    }
    
    // If no specific fact is found, return the default fact
    return colombiaFacts.default;
  }
  
  // We'll continue to add more municipalities to this database over time
  // This is version 1.0 of the Colombia Facts database